In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
pd.set_option("max_columns",100)
pd.set_option('display.width',1000)
pd.set_option('max_colwidth', 1000) 
import os


C:\Users\Ali\.conda\envs\tensor_ali\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Ali\.conda\envs\tensor_ali\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Users\Ali\.conda\envs\tensor_ali\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
path = os.path.join('C:/BEPEC Python Material/NLP project/','Clean_data.pkl')
df = pd.read_pickle(path)
df.head()

Lead Name   Location  Status                                                                                                                                                            Status information                                                                                                                        Clean-status                                                                                                       clean_sent                                                                                                                                Text
0           Raja  hyderabad        0                                        14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now                              [prema, share, detail, available, evng, prema, postpone, plan, train, currently, prema, not, interest]                         prema share detail available evng prema postpone plan train currently prema not interest                             hyderabad prema share detail available evng prema postpone plan train currently prema not interest Raja
1  Anirudh Reddy       pune        0  14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification  [prema, cal, share, detail, email, prema, share, detail, email, check, n, revert, prema, receive, email, look, asq, certification]  prema cal share detail email prema share detail email check n revert prema receive email look asq certification  pune prema cal share detail email prema share detail email check n revert prema receive email look asq certification Anirudh Reddy
2   Sapna Dewani  bangalore        1                                                                                                                                                             16|AuG|moHan:rnr                                                                                                                   [aug, mohan, rnr]                                                                                                    aug mohan rnr                                                                                                bangalore aug mohan rnr Sapna Dewani
3         suresh     mumbai        0                                                                                       14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server                                                            [surendra, want, server, aug, mohan, cal, busy, aug, mohan, reg, server]                                                     surendra want server aug mohan cal busy aug mohan reg server                                                          mumbai surendra want server aug mohan cal busy aug mohan reg server suresh
4  Akshay Shinde  hyderabad        0                                                       14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details                                           [prema, rnr, prema, give, info, say, revert, hr, prema, plan, next, month, share, detail]                                       prema rnr prema give info say revert hr prema plan next month share detail                                  hyderabad prema rnr prema give info say revert hr prema plan next month share detail Akshay Shinde

In [3]:
import sklearn
from sklearn.model_selection import train_test_split

In [4]:
X_train , X_test , y_train , y_test = train_test_split(df['Text'],df['Status '],test_size = 0.2,random_state = 42,shuffle= True,
                                                      stratify = df['Status '])
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_test.value_counts())

(739,)
(185,)
(739,)
(185,)
0    161
1     24
Name: Status , dtype: int64


In [22]:
from tqdm import tqdm
import nltk
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [23]:
def create_corpus(df):
    corpus=[]
    for text in tqdm(df):
        words=[word for word in word_tokenize(text)]
        corpus.append(words)
    return corpus

In [24]:
train_corpus = create_corpus(X_train)
test_corpus = create_corpus(X_test)
test_corpus[:5]

100%|██████████████████████████████████████████████████████████████████████████████| 185/185 [00:00<00:00, 3777.79it/s]


[['mumbai',
  'surendra',
  'call',
  'hour',
  'surendra',
  'rnr',
  'surendra',
  'sit',
  'work',
  'confirm',
  'time',
  'surendra',
  'check',
  'tomorrow',
  'pm',
  'session',
  'surendra',
  'come',
  'pm',
  'today',
  'surendra',
  'already',
  'do',
  'Vikas'],
 ['hyderabad',
  'june',
  'mohan',
  'rnr',
  'nd',
  'cal',
  'latr',
  'june',
  'mohan',
  'rnr',
  'nd',
  'not',
  'intrstd',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'july',
  'mohan',
  'rnr',
  'Akansha'],
 ['hyderabad',
  'july',
  'mohan',
  'rnr',
  'july',
  'mohan',
  'not',
  'july',
  'mohan',
  'cal',
  'evng',
  'aug',
  'mohan',
  'not',
  'intrtstd',
  'Vipra',
  'Deshpande'],
 ['bangalore',
  'surendra',
  'iam',
  'available',
  'next',
  'week',
  'tuesday',
  'morning',
  'better',
  'attend',
  'trail',
  'sessions',
  'please',
  'send',
  'detail',
  'prema',
  'pm',
  'check',
  'call',
  'prema',
  'need',
  'call',
  'pm',
  'prema',
  'rnr',
  'prema',
  'right',
 

In [25]:
tokenizer_obj = Tokenizer() 
tokenizer_obj.fit_on_texts(train_corpus) # methods `texts_to_sequences` or `texts_to_matrix`.
train_sequences=tokenizer_obj.texts_to_sequences(train_corpus) # Transforms each text in texts to a sequence of integers.
test_sequences=tokenizer_obj.texts_to_sequences(test_corpus)

test_sequences[:5]

[[33,
  2,
  8,
  420,
  2,
  1,
  2,
  429,
  100,
  70,
  42,
  2,
  17,
  31,
  29,
  24,
  2,
  35,
  29,
  21,
  2,
  58,
  78],
 [12,
  15,
  4,
  1,
  39,
  26,
  154,
  15,
  4,
  1,
  39,
  9,
  36,
  15,
  4,
  1,
  15,
  4,
  1,
  11,
  4,
  1,
  967],
 [12, 11, 4, 1, 11, 4, 9, 11, 4, 26, 59, 20, 4, 9, 538, 1356],
 [10,
  2,
  28,
  87,
  73,
  83,
  1627,
  61,
  115,
  27,
  163,
  84,
  54,
  55,
  7,
  3,
  29,
  17,
  8,
  3,
  18,
  8,
  29,
  3,
  1,
  3,
  219,
  285,
  531,
  16,
  112,
  144,
  16,
  77,
  1061,
  282],
 [3, 6, 7, 18, 26, 48, 29, 3, 1, 13, 9, 113]]

In [9]:
train_pad=pad_sequences(train_sequences,maxlen=50,truncating='post',padding='pre') # lists to array form
test_pad=pad_sequences(test_sequences,maxlen=50,truncating='post',padding='pre')

print(len(train_corpus))
print(train_pad.shape)
train_pad

739
(739, 50)


array([[   0,    0,    0, ...,   37,   22,  564],
       [   0,    0,    0, ...,   30,  565,  391],
       [   0,    0,    0, ...,   38,  566,  567],
       ...,
       [   0,    0,    0, ..., 1651, 1652, 1653],
       [   0,    0,    0, ...,  102,  148, 1655],
       [   0,    0,    0, ...,    6,    7,  274]])

In [10]:
word_index=tokenizer_obj.word_index
lenght = len(word_index)+1
print('Number of unique words:',lenght)

Number of unique words: 1656


####  We will be training 2 different NLP models 1 learns embedding from scratch and 2 uses pre-trained embedding and finnaly we see the performance of both models

In [11]:
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import *


In [12]:
## WE have to downgrade our numpy outherwise the below cell will give a NotImplementedError
#pip install numpy==1.19.5


In [13]:
import numpy as np
print(np.__version__)

1.19.5


## Defining the model

In [16]:
DIM = 100
MAX_LEN = 50
model = Sequential()

## Embedding layer
model.add(Embedding(lenght , DIM , input_length = MAX_LEN , trainable=True))
model.compile('adam' , 'mse')

## LSTM layer
model.add(LSTM(128,return_sequences=True,dropout=0.2))

#Global Maxpooling
model.add(GlobalMaxPooling1D())

#Dense Layer
model.add(Dense(64,activation='relu')) 
model.add(Dense(1,activation='sigmoid')) 

#Add loss function, metrics, optimizer
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=["acc"]) 

#Adding callbacks
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)  
mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1)

#Model summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 50, 100)           165600    
_________________________________________________________________
lstm (LSTM)                  (None, 50, 128)           117248    
_________________________________________________________________
global_max_pooling1d (Global (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 291,169
Trainable params: 291,169
Non-trainable params: 0
_________________________________________________________________


In [17]:
history = model.fit(np.array(train_pad),np.array(y_train),batch_size=128,epochs=10,
                    validation_data=(np.array(test_pad),np.array(y_test)),verbose=1,callbacks=[es,mc])

Epoch 1/10
6/6 [==============================] - 7s 612ms/step - loss: 0.6575 - acc: 0.8573 - val_loss: 0.5168 - val_acc: 0.8703

Epoch 00001: val_acc improved from -inf to 0.87027, saving model to best_model.h5
Epoch 2/10
6/6 [==============================] - 1s 221ms/step - loss: 0.4667 - acc: 0.8638 - val_loss: 0.4088 - val_acc: 0.8703

Epoch 00002: val_acc did not improve from 0.87027
Epoch 3/10
6/6 [==============================] - 1s 219ms/step - loss: 0.3884 - acc: 0.8757 - val_loss: 0.3875 - val_acc: 0.8703

Epoch 00003: val_acc did not improve from 0.87027
Epoch 4/10
6/6 [==============================] - 2s 299ms/step - loss: 0.3986 - acc: 0.8685 - val_loss: 0.3854 - val_acc: 0.8703

Epoch 00004: val_acc did not improve from 0.87027
Epoch 5/10
6/6 [==============================] - 1s 230ms/step - loss: 0.4012 - acc: 0.8622 - val_loss: 0.3823 - val_acc: 0.8703

Epoch 00005: val_acc did not improve from 0.87027
Epoch 6/10
6/6 [==============================] - 1s 223ms/step

In [14]:
#loading best model
from tensorflow.keras.models import load_model
model = load_model('best_model.h5')

#evaluation 
_,val_acc = model.evaluate(train_pad,y_train, batch_size=128)
print(val_acc)

6/6 [==============================] - 2s 71ms/step - loss: 0.5210 - acc: 0.8674
0.8673883676528931


In [18]:
# model.predict_classes(X_test) to get classes directly
y_pred = model.predict(train_pad)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train , y_pred)
cm

array([[641,   0],
       [ 98,   0]], dtype=int64)

In [19]:
y_pred = model.predict(test_pad)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[161,   0],
       [ 24,   0]], dtype=int64)

## Using-pre trained model (glove)

In [20]:
GLOVE_DIR = 'C:/Users/Ali/Downloads/glove.6B_2'
print("indexing words....")
glove_input_file = 'glove.6B.100d.txt'

f = open(os.path.join(GLOVE_DIR , glove_input_file),encoding='utf8')
embedding_index = {}
for line in f:
    values = line.split()
    word = values[0]
    ceof = np.asarray(values[1:] , dtype = 'float32')
    embedding_index[word] = ceof
f.close()

indexing words....


In [27]:
# create a weight matrix for words in training docs
embedding_matrix = np.zeros((lenght, 100))
for word, i in tokenizer_obj.word_index.items():
    print(word,i)

rnr 1
surendra 2
prema 3
mohan 4
soma 5
share 6
detail 7
call 8
not 9
bangalore 10
july 11
hyderabad 12
gowtham 13
demo 14
june 15
may 16
check 17
need 18
join 19
aug 20
today 21
back 22
want 23
session 24
busy 25
cal 26
attend 27
iam 28
pm 29
interest 30
tomorrow 31
u 32
mumbai 33
pune 34
come 35
intrstd 36
get 37
connect 38
nd 39
mail 40
classroom 41
time 42
try 43
ct 44
delhi 45
revert 46
link 47
later 48
n 49
weekend 50
switch 51
even 52
wil 53
please 54
send 55
ask 56
disconnect 57
already 58
evng 59
know 60
morning 61
reachable 62
look 63
us 64
say 65
let 66
train 67
swtch 68
email 69
confirm 70
reachble 71
month 72
next 73
batch 74
go 75
monday 76
plan 77
do 78
online 79
chennai 80
cls 81
inform 82
week 83
sessions 84
trainer 85
mrg 86
available 87
number 88
webinar 89
apr 90
kumar 91
present 92
aftr 93
th 94
record 95
meet 96
issue 97
mrng 98
course 99
work 100
travel 101
institute 102
dont 103
ofc 104
enrol 105
singh 106
nxt 107
due 108
unable 109
coverage 110
area 111
b 112
i

sumasree 1024
conncted 1025
prem 1026
fald 1027
lon 1028
yesterdy 1029
swtych 1030
anothr 1031
strts 1032
anitha 1033
philips 1034
suprt 1035
chakri 1036
pay 1037
arpit 1038
sowkhya 1039
wednsdy 1040
malarvizhi 1041
sep 1042
vikash 1043
sameer 1044
vaidya 1045
onlne 1046
soundarya 1047
aksah 1048
banerjee 1049
chengu 1050
behanan 1051
bellam 1052
notr 1053
diconecting 1054
pranali 1055
raul 1056
om 1057
site 1058
europe 1059
donno 1060
varun 1061
chandu 1062
shailee 1063
bose 1064
onkar 1065
khanapure 1066
amish 1067
see 1068
madhav 1069
yadagiri 1070
rao 1071
rafi 1072
sivarama 1073
sattibabu 1074
vinti 1075
rastogi 1076
shanker 1077
den 1078
phukan 1079
narendra 1080
guru 1081
lavanya 1082
emailid 1083
febian 1084
correia 1085
pwr 1086
swth 1087
sreenivasa 1088
nr 1089
placements 1090
nagendra 1091
wi 1092
sudheer 1093
kanishka 1094
ms 1095
dynamics 1096
ax 1097
vinoth 1098
nagappa 1099
trid 1100
dfrnt 1101
numbrs 1102
drope 1103
satish 1104
gurdeep 1105
learng 1106
thirumala 1107
c 

In [32]:
for word, i in tokenizer_obj.word_index.items():
    try:
        embedding_vector = embeddings_index.get(word)
        if embedding_vector:
            embedding_matrix[i] = embedding_vector
    except:
        pass

## Defining the model

In [41]:
model=Sequential()

#embedding layer
model.add(Embedding(lenght,100,weights=[embedding_matrix],input_length=100,trainable=False)) 
model.add(Dense())
#lstm layer
model.add(LSTM(128,return_sequences=True,dropout=0.2))

#Global Maxpooling
model.add(GlobalMaxPooling1D())

#Dense Layer
model.add(Dense(64,activation='relu')) 
model.add(Dense(1,activation='sigmoid')) 

#Add loss function, metrics, optimizer
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=["acc"]) 

#Adding callbacks
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)  
mc=ModelCheckpoint('best_model.h4', monitor='val_acc', mode='max', save_best_only=True,verbose=1)  

#Print summary of model
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 100)          165600    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100, 128)          117248    
_________________________________________________________________
global_max_pooling1d_2 (Glob (None, 128)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
Total params: 291,169
Trainable params: 125,569
Non-trainable params: 165,600
_________________________________________________________________
None


In [37]:
history = model.fit(np.array(train_pad),np.array(y_train),batch_size=128,epochs=10,
                    validation_data=(np.array(test_pad),np.array(y_test)),verbose=1,callbacks=[es,mc])

Epoch 1/10
6/6 [==============================] - 6s 382ms/step - loss: 0.6926 - acc: 0.8523 - val_loss: 0.6909 - val_acc: 0.8703

Epoch 00001: val_acc improved from -inf to 0.87027, saving model to best_model.h4


INFO:tensorflow:Assets written to: best_model.h4\assets


INFO:tensorflow:Assets written to: best_model.h4\assets


Epoch 2/10
6/6 [==============================] - 1s 257ms/step - loss: 0.6903 - acc: 0.8832 - val_loss: 0.6887 - val_acc: 0.8703

Epoch 00002: val_acc did not improve from 0.87027
Epoch 3/10
6/6 [==============================] - 1s 195ms/step - loss: 0.6883 - acc: 0.8633 - val_loss: 0.6865 - val_acc: 0.8703

Epoch 00003: val_acc did not improve from 0.87027
Epoch 4/10
6/6 [==============================] - 1s 228ms/step - loss: 0.6862 - acc: 0.8605 - val_loss: 0.6844 - val_acc: 0.8703

Epoch 00004: val_acc did not improve from 0.87027
Epoch 5/10
6/6 [==============================] - 1s 244ms/step - loss: 0.6836 - acc: 0.8826 - val_loss: 0.6822 - val_acc: 0.8703

Epoch 00005: val_acc did not improve from 0.87027
Epoch 6/10
6/6 [==============================] - 1s 208ms/step - loss: 0.6822 - acc: 0.8541 - val_loss: 0.6800 - val_acc: 0.8703

Epoch 00006: val_acc did not improve from 0.87027
Epoch 7/10
6/6 [==============================] - 1s 246ms/step - loss: 0.6795 - acc: 0.8725 - 

In [38]:
#loading best model
from tensorflow.keras.models import load_model
model = load_model('best_model.h4')

#evaluation 
_,val_acc = model.evaluate(train_pad,y_train, batch_size=128)
print(val_acc)

6/6 [==============================] - 1s 75ms/step - loss: 0.6909 - acc: 0.8674
0.8673883676528931


In [39]:
y_pred = model.predict(train_pad)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train , y_pred)
cm

array([[641,   0],
       [ 98,   0]], dtype=int64)

In [40]:
y_pred = model.predict(test_pad)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[161,   0],
       [ 24,   0]], dtype=int64)