In [1]:
import pandas as pd
import numpy as np
pd.set_option('max_colwidth',1000)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer as wnl
import re
stpwrds = set(stopwords.words('english'))
print(len(stpwrds))
stpwrds.discard('not')
print(len(stpwrds))


179
178


In [2]:
df = pd.read_excel(r'C:\BEPEC Python Material\NLP,Naive Baise,SVM\NLP project\1000 leads.xlsx')
df

Lead Name   Location        Status   \
0                    Raja  hyderabad  Not Converted   
1           Anirudh Reddy       pune  Not Converted   
2            Sapna Dewani  bangalore     Converted    
3                  suresh     mumbai  Not Converted   
4           Akshay Shinde  hyderabad  Not Converted   
...                   ...        ...            ...   
996                 vipin  bangalore  Not Converted   
997               dheeraj    chennai  Not Converted   
998         kuldeep singh  bangalore  Not Converted   
999          ankur sharma  bangalore  Not Converted   
1000  Saugata Chakrabarti  bangalore  Not Converted   

                                                                                                                                                                                                                                                                                                                                                                                                                        Status information  \
0                                                                                                                                                                                                                                                                                                    14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now   
1                                                                                                                                                                                                                                                              14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification   
2                                                                                                                                                                                                                                                                                                                                                                                                                         16|AuG|moHan:rnr   
3                                                                                                                                                                                                                                                                                                                                                   14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server   
4                                                                                                                                                                                                                                                                                                                   14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details   
...                                                                                                                                                                                                                                                                                                                                                                                                                                    ...   
996                                                                                                                                                                                                                                                                                            25/4/17(Surendra):please send me details tomorrow afternoo

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Lead Name           1001 non-null   object 
 1   Location            980 non-null    object 
 2   Status              998 non-null    object 
 3   Status information  977 non-null    object 
 4   Unnamed: 4          0 non-null      float64
dtypes: float64(1), object(4)
memory usage: 39.2+ KB


In [4]:
df['Status '].value_counts()

Not Converted    856
Converted        124
NOt Converted     11
Conveted           7
Name: Status , dtype: int64

In [5]:
df['Status '].replace(to_replace=['NOt Converted','Conveted'], value=['Not Converted','Converted '], inplace=True)
df['Status '].value_counts()

Not Converted    867
Converted        131
Name: Status , dtype: int64

In [6]:
df.columns[-1]

'Unnamed: 4'

In [7]:
df.drop(columns={df.columns[-1]}, inplace=True)
df.sample(10)

Lead Name   Location        Status   \
434         Bhaskar  bangalore  Not Converted   
703  Dhwaj Dronawat  hyderabad  Not Converted   
334          Ananya  hyderabad     Converted    
707            Ravi     mumbai  Not Converted   
957       harish SN  hyderabad  Not Converted   
981       ranganath      noida  Not Converted   
390      Anjaneyulu  hyderabad  Not Converted   
833    Nitish Kumar     mumbai  Not Converted   
985       venkatesh  bangalore  Not Converted   
371           Karan  bangalore     Converted    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Status information  
434                                                                                                                                                                                                                                                                                                                                                                                                                                                            5/JulY/moHan: offce prvdng  
703                                                                                                                                                                             29/5/17(prema): student, shared ds details; require on weekends 3/6/17(prema): need demo after 5th 6/6/17(prema): call got disconnected due to n/w isue 8/6/17(prema): wil check with profesor n inform 13/6/17(prema): shared webinar details 16/6/17(prema): shared weekend details 17/6/17(prema): RNR  
334                                                                                                                                                                                                                                                                                                                                                                                                                      11/7/17(soma):Details Shared 13/7/17(prema): i'l revert on email  
707                                                                                                                                                                                                                                                                                                                         29/5/17(prema): gave info on ssgb; waiting for emailid as he said he wil text 30/5/17(prema): rnr 12/6/17(prema): shared details 17/7/17(prema): ssgb CT only  
957                                                                                                                                                                                                                                                                                                                                                                                                              25/Apr/moHan:he will come 16/MaY/moHan:rechd hom by lat ni8 timng issues  
981                                                                                                                                                                                                                                                                                                                                                                24/4/17(prema): fresher, shared details 25/4/17(prema): busy now, cal later 18/7/17(prema): not looking for any course  
390  5/7/17(soma):present he is out of hyderabad,details shared,and need to call on monday 11/7/17(soma):RNR 14/7/17(SOMA):Still he didnt 

In [8]:
df.dropna(axis=0 , inplace=True)
print(df.shape)
print(df['Status '].value_counts())
df.info()
df.reset_index(drop=True)

(956, 4)
Not Converted    829
Converted        127
Name: Status , dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 956 entries, 0 to 1000
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Lead Name           956 non-null    object
 1   Location            956 non-null    object
 2   Status              956 non-null    object
 3   Status information  956 non-null    object
dtypes: object(4)
memory usage: 37.3+ KB


Lead Name   Location        Status   \
0                   Raja  hyderabad  Not Converted   
1          Anirudh Reddy       pune  Not Converted   
2           Sapna Dewani  bangalore     Converted    
3                 suresh     mumbai  Not Converted   
4          Akshay Shinde  hyderabad  Not Converted   
..                   ...        ...            ...   
951                vipin  bangalore  Not Converted   
952              dheeraj    chennai  Not Converted   
953        kuldeep singh  bangalore  Not Converted   
954         ankur sharma  bangalore  Not Converted   
955  Saugata Chakrabarti  bangalore  Not Converted   

                                                                                                                                                                                                                                                                                                                                                                                                                       Status information  
0                                                                                                                                                                                                                                                                                                   14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now  
1                                                                                                                                                                                                                                                             14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification  
2                                                                                                                                                                                                                                                                                                                                                                                                                        16|AuG|moHan:rnr  
3                                                                                                                                                                                                                                                                                                                                                  14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server  
4                                                                                                                                                                                                                                                                                                                  14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details  
..                                                                                                                                                                                                                                                                                                                                                                                                                                    ...  
951                                                                                                                                                                                                                                                                                           25/4/17(Surendra):please send me details tomorrow afternoon 12pm we will discuss 12/

In [9]:
import string
#stpwrds = set(stopwords.words('english'))
stpwrds.update(['endnan','nan','end','r','im','bt','tmrw'])

def clean_text(text):  
    #no_punctuation = [char for char in text if char not in string.punctuation]
    #print(no_punctuation)
    #no_punctuation1 = ''.join(no_punctuation)
    #print(no_punctuation1)
    text = str(text)
    words = re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", " ", text )  
    pattren = r"[\d]"
    words = re.sub(pattren, '', words)
    words = words.lower()
    final_words =  [wnl().lemmatize(word , pos = 'v') for word in words.split() if word not in stpwrds]
    return(final_words)


In [10]:
df['Clean-status'] = df['Status information'].apply(clean_text)
df.head()

Lead Name   Location        Status   \
0           Raja  hyderabad  Not Converted   
1  Anirudh Reddy       pune  Not Converted   
2   Sapna Dewani  bangalore     Converted    
3         suresh     mumbai  Not Converted   
4  Akshay Shinde  hyderabad  Not Converted   

                                                                                                                                                            Status information  \
0                                        14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now   
1  14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification   
2                                                                                                                                                             16|AuG|moHan:rnr   
3                                                                                       14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server   
4                                                       14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details   

                                                                                                                         Clean-status  
0                              [prema, share, detail, available, evng, prema, postpone, plan, train, currently, prema, not, interest]  
1  [prema, cal, share, detail, email, prema, share, detail, email, check, n, revert, prema, receive, email, look, asq, certification]  
2                                                                                                                   [aug, mohan, rnr]  
3                                                            [surendra, want, server, aug, mohan, cal, busy, aug, mohan, reg, server]  
4                                           [prema, rnr, prema, give, info, say, revert, hr, prema, plan, next, month, share, detail]

In [11]:
def sent_tokenize(text):
    text = ' '.join(text)
    return(text)
df['clean_sent'] = df['Clean-status'].apply(sent_tokenize)
df.head()

Lead Name   Location        Status   \
0           Raja  hyderabad  Not Converted   
1  Anirudh Reddy       pune  Not Converted   
2   Sapna Dewani  bangalore     Converted    
3         suresh     mumbai  Not Converted   
4  Akshay Shinde  hyderabad  Not Converted   

                                                                                                                                                            Status information  \
0                                        14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now   
1  14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification   
2                                                                                                                                                             16|AuG|moHan:rnr   
3                                                                                       14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server   
4                                                       14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details   

                                                                                                                         Clean-status  \
0                              [prema, share, detail, available, evng, prema, postpone, plan, train, currently, prema, not, interest]   
1  [prema, cal, share, detail, email, prema, share, detail, email, check, n, revert, prema, receive, email, look, asq, certification]   
2                                                                                                                   [aug, mohan, rnr]   
3                                                            [surendra, want, server, aug, mohan, cal, busy, aug, mohan, reg, server]   
4                                           [prema, rnr, prema, give, info, say, revert, hr, prema, plan, next, month, share, detail]   

                                                                                                        clean_sent  
0                         prema share detail available evng prema postpone plan train currently prema not interest  
1  prema cal share detail email prema share detail email check n revert prema receive email look asq certification  
2                                                                                                    aug mohan rnr  
3                                                     surendra want server aug mohan cal busy aug mohan reg server  
4                                       prema rnr prema give info say revert hr prema plan next month share detail

In [12]:
print(df.shape)
df.drop_duplicates(subset=['clean_sent'], inplace=True)
print(df.shape)

(956, 6)
(924, 6)


In [13]:
df['Text'] = df['Location']+' '+df['clean_sent']+' '+df['Lead Name']
df.head()

Lead Name   Location        Status   \
0           Raja  hyderabad  Not Converted   
1  Anirudh Reddy       pune  Not Converted   
2   Sapna Dewani  bangalore     Converted    
3         suresh     mumbai  Not Converted   
4  Akshay Shinde  hyderabad  Not Converted   

                                                                                                                                                            Status information  \
0                                        14/8/prema: share me details, available in evng 18/8/prema: postponed the plans for training currently 9/11/prema: not interested now   
1  14/8/prema: cal me tmrw, shared details to email 16/8/prema: share details to email, will check n revert 18/8/prema: received your email, i'm looking for ASQ certification   
2                                                                                                                                                             16|AuG|moHan:rnr   
3                                                                                       14/8/17(Surendra):i want only Server 16|AuG|moHan:cal busy 17|AuG|moHan:reg for server   
4                                                       14/8/prema:rnr 16/8/prema: gave info, he said he will revert in 1hr 30/8/prema: planning for next month, share details   

                                                                                                                         Clean-status  \
0                              [prema, share, detail, available, evng, prema, postpone, plan, train, currently, prema, not, interest]   
1  [prema, cal, share, detail, email, prema, share, detail, email, check, n, revert, prema, receive, email, look, asq, certification]   
2                                                                                                                   [aug, mohan, rnr]   
3                                                            [surendra, want, server, aug, mohan, cal, busy, aug, mohan, reg, server]   
4                                           [prema, rnr, prema, give, info, say, revert, hr, prema, plan, next, month, share, detail]   

                                                                                                        clean_sent  \
0                         prema share detail available evng prema postpone plan train currently prema not interest   
1  prema cal share detail email prema share detail email check n revert prema receive email look asq certification   
2                                                                                                    aug mohan rnr   
3                                                     surendra want server aug mohan cal busy aug mohan reg server   
4                                       prema rnr prema give info say revert hr prema plan next month share detail   

                                                                                                                                 Text  
0                             hyderabad prema share detail available evng prema postpone plan train currently prema not interest Raja  
1  pune prema cal share detail email prema share detail email check n revert prema receive email look asq certification Anirudh Reddy  
2                                                                                                bangalore aug mohan rnr Sapna Dewani  
3                                                          mumbai surendra want server aug mohan cal busy aug mohan reg server suresh  
4                                  hyderabad prema rnr prema give info say revert hr prema plan next month share detail Akshay Shinde

In [14]:
df['Status '].replace(to_replace=['Converted ','Not Converted'], value=[int(1),int(0)], inplace=True)
df['Status '].value_counts()

0    802
1    122
Name: Status , dtype: int64

In [15]:
from gensim.models import Word2Vec, word2vec
import logging  # Setting up the loggings to monitor gensim
logging.basicConfig(format="%(levelname)s - %(asctime)s: %(message)s", datefmt= '%H:%M:%S', level=logging.INFO)
from sklearn.model_selection import train_test_split

In [16]:
X_train , X_test , y_train , y_test = train_test_split(df['Text'],df['Status '],test_size = 0.2,random_state = 42,shuffle= True)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(739,)
(185,)
(739,)
(185,)


In [18]:
sentences = []
for i in X_train:
    tokens = i.split(' ')
    l = list(tokens)
    sentences.append(l)
sentences

[['bangalore',
  'surendra',
  'share',
  'link',
  'surendra',
  'get',
  'back',
  'share',
  'office',
  'detail',
  'surendra',
  'rnr',
  'surendra',
  'wrong',
  'number',
  'call',
  'disconnect',
  'number',
  'correct',
  'surendra',
  'wrong',
  'number',
  'iam',
  'not',
  'abdul',
  'Abdul'],
 ['delhi',
  'soma',
  'not',
  'reachable',
  'mail',
  'send',
  'soma',
  'need',
  'month',
  'get',
  'back',
  'us',
  'soma',
  'want',
  'months',
  'Rajesh'],
 ['Hyderabad',
  'prema',
  'ct',
  'weekdays',
  'share',
  'detail',
  'summit',
  'surendra',
  'rnr',
  'prema',
  'share',
  'session',
  'detail',
  'prema',
  'rnr',
  'prema',
  'rnr',
  'prema',
  'rnr',
  'prema',
  'want',
  'ct',
  'ds',
  'ml',
  'dl',
  'k',
  'Samreen'],
 ['bangalore',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'july',
  '

In [29]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tqdm import tqdm
import nltk
from nltk.tokenize import word_tokenize


In [30]:
def create_corpus(df):
    corpus=[]
    for tweet in tqdm(df):
        words=[word for word in word_tokenize(tweet)]
        corpus.append(words)
    return corpus

In [36]:
word = 'ali'
#word.isalnum() return true is string is alpha numeric
#word.isalpha() return true is string is alphabet
corpus = create_corpus(X_train)
corpus

100%|██████████████████████████████████████████████████████████████████████████████| 739/739 [00:00<00:00, 3554.34it/s]


[['bangalore',
  'surendra',
  'share',
  'link',
  'surendra',
  'get',
  'back',
  'share',
  'office',
  'detail',
  'surendra',
  'rnr',
  'surendra',
  'wrong',
  'number',
  'call',
  'disconnect',
  'number',
  'correct',
  'surendra',
  'wrong',
  'number',
  'iam',
  'not',
  'abdul',
  'Abdul'],
 ['delhi',
  'soma',
  'not',
  'reachable',
  'mail',
  'send',
  'soma',
  'need',
  'month',
  'get',
  'back',
  'us',
  'soma',
  'want',
  'months',
  'Rajesh'],
 ['Hyderabad',
  'prema',
  'ct',
  'weekdays',
  'share',
  'detail',
  'summit',
  'surendra',
  'rnr',
  'prema',
  'share',
  'session',
  'detail',
  'prema',
  'rnr',
  'prema',
  'rnr',
  'prema',
  'rnr',
  'prema',
  'want',
  'ct',
  'ds',
  'ml',
  'dl',
  'k',
  'Samreen'],
 ['bangalore',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'june',
  'mohan',
  'rnr',
  'july',
  '

In [34]:
GLOVE_DIR = 'C:/Users/Ali/Downloads/glove.6B_2'
print("indexing words....")
glove_input_file = 'glove.6B.100d.txt'
word2vec_output_file = 'glove.6B.100d.txt.word2vec'

f = open(os.path.join(GLOVE_DIR , glove_input_file),encoding='utf8')
embedding_index = {}
for line in f:
    values = line.split()
    word = values[0]
    ceof = np.asarray(values[1:] , dtype = 'float32')
    embedding_index[word] = ceof
f.close()

indexing words....


<IPython.core.display.Javascript object>

In [42]:
MAX_LEN=50
tokenizer_obj=Tokenizer()
tokenizer_obj.fit_on_texts(corpus) # Required before using `texts_to_sequences` or `texts_to_matrix`.
print(tokenizer_obj)
sequences=tokenizer_obj.texts_to_sequences(corpus) # Transforms each text in texts to a sequence of integers.
sequences

[[10,
  2,
  6,
  48,
  2,
  33,
  19,
  6,
  152,
  7,
  2,
  1,
  2,
  182,
  85,
  8,
  51,
  85,
  572,
  2,
  182,
  85,
  32,
  9,
  203,
  203],
 [49, 5, 9, 58, 37, 53, 5, 18, 86, 33, 19, 59, 5, 24, 136, 153],
 [12,
  3,
  41,
  289,
  6,
  7,
  573,
  2,
  1,
  3,
  6,
  23,
  7,
  3,
  1,
  3,
  1,
  3,
  1,
  3,
  24,
  41,
  137,
  166,
  574,
  120,
  575],
 [10,
  15,
  4,
  1,
  15,
  4,
  1,
  15,
  4,
  1,
  15,
  4,
  1,
  15,
  4,
  1,
  15,
  4,
  1,
  15,
  4,
  1,
  11,
  4,
  1,
  20,
  4,
  1,
  576],
 [12, 98, 4, 1, 16, 4, 26, 29, 16, 4, 18, 81, 167, 111, 25, 14, 204],
 [34, 2, 6, 7, 2, 6, 7, 2, 1, 2, 63, 53, 48, 2, 8, 28, 19, 26, 51, 2, 1, 394],
 [10, 3, 18, 26, 29, 3, 9, 58, 577],
 [10,
  20,
  4,
  1,
  20,
  4,
  1,
  20,
  4,
  1,
  20,
  4,
  18,
  14,
  395,
  290,
  17,
  25,
  14,
  20,
  4,
  47,
  20,
  4,
  25,
  104,
  20,
  4,
  39,
  121,
  92,
  578,
  291],
 [12, 2, 1, 37, 53, 2, 1, 1, 73, 579],
 [10, 3, 8, 29, 3, 580, 82, 26, 45, 3, 1, 3, 93, 6

In [43]:
tweet_pad=pad_sequences(sequences,maxlen=MAX_LEN,truncating='post',padding='post') # lists to array form
print(len(corpus))
print(tweet_pad.shape)
tweet_pad

739
(739, 50)


array([[10,  2,  6, ...,  0,  0,  0],
       [49,  5,  9, ...,  0,  0,  0],
       [12,  3, 41, ...,  0,  0,  0],
       ...,
       [34,  2,  8, ...,  0,  0,  0],
       [10,  3, 96, ...,  0,  0,  0],
       [10, 20,  4, ...,  0,  0,  0]])

In [47]:
sequence = [[1], [2, 40], [4, 5, 6]]
print(pad_sequences(sequence),"\n")
print(pad_sequences(sequence,maxlen = 2))


[[ 0  0  1]
 [ 0  2 40]
 [ 4  5  6]] 

[[ 0  1]
 [ 2 40]
 [ 5  6]]


In [48]:
word_index=tokenizer_obj.word_index
word_index
print('Number of unique words:',len(word_index))

Number of unique words: 1659


In [50]:
word_index

{'rnr': 1,
 'surendra': 2,
 'prema': 3,
 'mohan': 4,
 'soma': 5,
 'share': 6,
 'detail': 7,
 'call': 8,
 'not': 9,
 'bangalore': 10,
 'july': 11,
 'hyderabad': 12,
 'gowtham': 13,
 'demo': 14,
 'june': 15,
 'may': 16,
 'check': 17,
 'need': 18,
 'back': 19,
 'aug': 20,
 'busy': 21,
 'join': 22,
 'session': 23,
 'want': 24,
 'today': 25,
 'cal': 26,
 'interest': 27,
 'u': 28,
 'pm': 29,
 'attend': 30,
 'mumbai': 31,
 'iam': 32,
 'get': 33,
 'pune': 34,
 'intrstd': 35,
 'tomorrow': 36,
 'mail': 37,
 'connect': 38,
 'n': 39,
 'nd': 40,
 'ct': 41,
 'switch': 42,
 'revert': 43,
 'classroom': 44,
 'later': 45,
 'come': 46,
 'try': 47,
 'link': 48,
 'delhi': 49,
 'time': 50,
 'disconnect': 51,
 'wil': 52,
 'send': 53,
 'email': 54,
 'ask': 55,
 'even': 56,
 'know': 57,
 'reachable': 58,
 'us': 59,
 'weekend': 60,
 'let': 61,
 'look': 62,
 'please': 63,
 'evng': 64,
 'already': 65,
 'train': 66,
 'say': 67,
 'swtch': 68,
 'morning': 69,
 'confirm': 70,
 'online': 71,
 'plan': 72,
 'batch': 73,

In [52]:
num_words=len(word_index)+1
embedding_matrix=np.zeros((num_words,100))

for word,i in tqdm(word_index.items()):
    if i > num_words:
        continue
    emb_vec=embedding_index.get(word)
    if emb_vec is not None:
        embedding_matrix[i]=emb_vec   
embedding_matrix

100%|██████████████████████████████████████████████████████████████████████████| 1659/1659 [00:00<00:00, 150917.44it/s]


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.097933  ,  0.02123   ,  0.083459  , ..., -0.51103997,
        -0.63529998,  0.1339    ],
       [ 0.072616  , -0.92613   , -0.086188  , ..., -0.49006   ,
        -0.47602999, -0.58427   ],
       ...,
       [-0.48231   , -0.092324  ,  0.28652   , ..., -0.013457  ,
        -1.05009997, -0.99941999],
       [ 0.63783997, -0.40312001, -0.42816001, ...,  0.04649   ,
        -0.67769998,  0.32185   ],
       [ 0.39971   , -0.27052   ,  0.39609   , ...,  0.10523   ,
         0.014917  ,  0.74334002]])

In [53]:
print(embedding_matrix.shape)

(1660, 100)


In [59]:
tweet_pad

array([[10,  2,  6, ...,  0,  0,  0],
       [49,  5,  9, ...,  0,  0,  0],
       [12,  3, 41, ...,  0,  0,  0],
       ...,
       [34,  2,  8, ...,  0,  0,  0],
       [10,  3, 96, ...,  0,  0,  0],
       [10, 20,  4, ...,  0,  0,  0]])

In [62]:
d_2 = pd.DataFrame(np.random.random(size = (40,4)))
d_2

0         1         2         3
0   0.010570  0.988242  0.949875  0.044826
1   0.591556  0.351220  0.084085  0.081966
2   0.043564  0.193303  0.478710  0.336542
3   0.252843  0.025907  0.136802  0.371457
4   0.805214  0.000765  0.044339  0.101392
5   0.460697  0.803532  0.923432  0.894524
6   0.452285  0.803065  0.241935  0.054079
7   0.077623  0.336375  0.839325  0.771797
8   0.724383  0.063444  0.785221  0.211814
9   0.115643  0.703872  0.617069  0.275845
10  0.170839  0.872538  0.282535  0.533232
11  0.304105  0.372970  0.907451  0.610884
12  0.076784  0.188534  0.424499  0.856262
13  0.501576  0.295051  0.867119  0.007482
14  0.278301  0.443923  0.632668  0.956704
15  0.833166  0.712733  0.772439  0.963965
16  0.413630  0.703835  0.376327  0.928109
17  0.611996  0.570447  0.978358  0.416434
18  0.658128  0.163135  0.194199  0.658315
19  0.695566  0.704202  0.965227  0.936572
20  0.221739  0.760760  0.456410  0.774984
21  0.842098  0.777643  0.188214  0.235378
22  0.847772  0.459839  0.805453  0.719068
23  0.955593  0.436152  0.855926  0.596794
24  0.389215  0.012378  0.307244  0.467123
25  0.554503  0.918627  0.183361  0.084459
26  0.562914  0.498605  0.675002  0.169512
27  0.278183  0.606608  0.836339  0.384839
28  0.930473  0.283375  0.490853  0.953177
29  0.296891  0.935707  0.878814  0.932102
30  0.597191  0.498146  0.305932  0.291383
31  0.868373  0.764326  0.557738  0.235684
32  0.242584  0.420739  0.057973  0.533281
33  0.461209  0.598974  0.284827  0.229573
34  0.691345  0.225595  0.707613  0.400320
35  0.344744  0.659907  0.956235  0.179773
36  0.963738  0.290228  0.036871  0.523515
37  0.907265  0.109359  0.422142  0.856788
38  0.390705  0.267722  0.020126  0.395157
39  0.107419  0.734221  0.818314  0.534737

In [66]:
print(d_2[3][:3]**2)
d_2[0][:3] = d_2[3][:3]**2
d_2.head()

0    0.002009
1    0.006718
2    0.113260
Name: 3, dtype: float64


0         1         2         3
0  0.002009  0.988242  0.949875  0.044826
1  0.006718  0.351220  0.084085  0.081966
2  0.113260  0.193303  0.478710  0.336542
3  0.252843  0.025907  0.136802  0.371457
4  0.805214  0.000765  0.044339  0.101392